import { PAGE_SIZE } from "@/core/api/common";

export const QUERY_DEBOUNCE_THRESHOLD = 500;
export const queryKeys = {
  FAVORITES: ["FAVORITES"],
  USER_PROFILE_STATS: ["USER_PROFILE_STATS"],
  BOOKINGS: ["BOOKINGS", PAGE_SIZE],
  PROPERTIES: ["PROPERTIES", PAGE_SIZE],
  NOTIFICATIONS: ["NOTIFICATIONS", PAGE_SIZE],
  USER_NOTIFICATIONS: ["USER_NOTIFICATIONS", PAGE_SIZE],
  PROPERTIES_SEARCH: "PROPERTIES_SEARCH",
  PROPERTY: "PROPERTY",
  FEATURED_PROPERTIES: ["FEATURED_PROPERTIES", PAGE_SIZE],
};
